# Generated by Django 3.2.7 on 2021-09-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0003_alter_pontoturistico_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='approved',
            new_name='aprovado',
        ),
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='name',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
